version: "3.3"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:9.6.23-stretch
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
        - postgres_data:/data/postgres
    ports:
      - 5432:5432
    networks:
      - conductor
    restart: unless-stopped

  conductor_api:
    image: conductor-api:latest
    container_name: conductor-api
    networks:
      - conductor
    volumes:
      - ./:/home/appuser/code
    ports:
      - "8000:8000"
    working_dir: /home/appuser/code
    command:
      python main.py

  resolve_dependencies:
    image: conductor-api:latest
    volumes:
      - ./:/home/appuser/code
    working_dir: /home/appuser/code
    networks:
      - conductor
    command: pip-compile -r ./requirements.direct
  
  bash:
    image: conductor-api:latest
    container_name: conductor-bash
    networks:
      - conductor
    working_dir: /home/appuser/code
    command: bash


networks:
  conductor:
    driver: bridge
    ipam:
      driver: default

volumes:
    postgres_data:
