version: "3.3"

services:
  bash:
    image: conductor:latest
    volumes:
      - ./:/app
    working_dir: /app
    command: bash

  server:
    image: conductor:latest
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
    command: node ./src/index.js

networks:
  conductor:
    driver: bridge
    ipam:
      driver: default
