version: "3.3"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres-db:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
        - postgres_data:/data/postgres
        - ./:/root/workspace
    ports:
      - 5432:5432
    networks:
      - conductor
    restart: unless-stopped


  conductor_api:
    image: conductor-api:latest
    container_name: conductor-api
    networks:
      - conductor
    volumes:
      - ./:/home/appuser/code
    ports:
      - "8000:8000"
    working_dir: /home/appuser/code
    command:
      uvicorn main:app --host 0.0.0.0 --port 8000 --workers 10


networks:
  conductor:
    driver: bridge
    ipam:
      driver: default


volumes:
    postgres_data:
